### ISSUE TITLE
Verify license compatibility with dependencies

### ISSUE THREAD

**Issue by ryan-jacobs** [Center-for-Research-Libraries/crl-serials-validator#17]
This relates to #5, but given that that issue is considering larger licensing best practices for CRL, it's best to address some project-specific considerations in a separate issue.

A strict interpretation of the GPL indicates that if we use any PyPl (pip) based dependencies that are GPL (but not LGPL) we need to be compatible with GPL. The legal considerations around this are not clear, and it may be safe to argue that because we are not distributing these dependencies (they are just references in requirements.txt, not included source code) we don't have to worry about this. However, the spirit of the GPL, and the Free Software Foundation, seem to say otherwise.

At least one dependency, urldecode (https://pypi.org/project/Unidecode/) is GPLv2. We should check if there are others or any other kinds of incompatibilities.

This may also mean that this project must be GPL independent of any outcomes of the larger CRL licensing strategies. We need to verify this.

**Comment by nflorin** [comment]
I'm marking this one as closed. Everything I've read suggests that having GPL dependencies requires a GPL license, even though no court case has proven that (yet).
