### ISSUE TITLE
colorize command line output

### ISSUE THREAD

**Issue by AndyElliottCRL** [Center-for-Research-Libraries/crl-serials-validator#23]
Specifics TBA but even before a GUI is ready we should be able to make the command line interface more user friendly by using colors and highlighting. 
Adding now as placeholder/don't forget for future.

**Comment by nflorin** [comment]
Most of the terminal interface has some colorizing to it. Still need to colorize the output of the quick scan and the output of the main run itself.

**Comment by nflorin** [comment]
![Screenshot_2022-01-06_16-49-54](https://user-images.githubusercontent.com/6247641/148457044-97bce8c7-f509-4c27-b98c-0d156c3dbc88.png)

**Comment by nflorin** [comment]
The current main menu (in VS Code's built in terminal under Linux):
![Screenshot_2022-01-06_16-53-31](https://user-images.githubusercontent.com/6247641/148457506-164fed33-7727-4735-81f6-fad87df3c923.png)

**Comment by nflorin** [comment]
Everything has at least preliminary coloring. I'll update as needed, but it should be good for now.
