### ISSUE TITLE
Add GPL License

### ISSUE THREAD

**Issue by ryan-jacobs** [Center-for-Research-Libraries/crl-serials-validator#53]
There have been no objections to our proposal to apply a GPL license to the project. We need to add the appropriate licensing file to the project to embed this license officially.

I believe that instructions on file/text content are here: https://choosealicense.com/licenses/gpl-3.0/

**Comment by ryan-jacobs** [comment]
It looks like this was addressed in #49, but then reverted.

**Comment by ryan-jacobs** [comment]
See PR #54.

**Comment by nflorin** [comment]
Done at last!
